import { LGACollationData, IncidentReport, PollingUnitRecord, BroadcastLog, ElectionStageMeta, PVTIReVAuditRecord } from '@/types/election';

export const KEBBI_LGAS: LGACollationData[] = [
  {
    id: 'lga-01',
    name: 'Birnin Kebbi',
    zone: 'Central',
    totalPUs: 275,
    reportedPUs: 268,
    registeredVoters: 165000,
    bivasAccredited: 78500,
    adcVotes: 52400,
    apcVotes: 24100,
    pdpVotes: 1200,
    rejectedVotes: 800,
    cancelledPVCs: 1850,
    status: 'WON',
    leadMargin: 28300,
    ec8cSigned: true,
    legalLeadName: 'Barr. Sanusi Dangaladima'
  },
  {
    id: 'lga-02',
    name: 'Aliero',
    zone: 'Central',
    totalPUs: 120,
    reportedPUs: 120,
    registeredVoters: 74000,
    bivasAccredited: 38200,
    adcVotes: 24800,
    apcVotes: 12100,
    pdpVotes: 850,
    rejectedVotes: 450,
    cancelledPVCs: 620,
    status: 'WON',
    leadMargin: 12700,
    ec8cSigned: true,
    legalLeadName: 'Barr. Murtala Aliero'
  },
  {
    id: 'lga-03',
    name: 'Jega',
    zone: 'Central',
    totalPUs: 185,
    reportedPUs: 172,
    registeredVoters: 112000,
    bivasAccredited: 55400,
    adcVotes: 31200,
    apcVotes: 22400,
    pdpVotes: 1100,
    rejectedVotes: 700,
    cancelledPVCs: 1200,
    status: 'LEADING',
    leadMargin: 8800,
    ec8cSigned: false,
    legalLeadName: 'Barr. Ahmad Jega'
  },
  {
    id: 'lga-04',
    name: 'Kalgo',
    zone: 'Central',
    totalPUs: 98,
    reportedPUs: 98,
    registeredVoters: 58000,
    bivasAccredited: 25800,
    adcVotes: 14600,
    apcVotes: 10200,
    pdpVotes: 600,
    rejectedVotes: 400,
    cancelledPVCs: 500,
    status: 'WON',
    leadMargin: 4400,
    ec8cSigned: true,
    legalLeadName: 'Barr. Bello Kalgo'
  },
  {
    id: 'lga-05',
    name: 'Gwandu',
    zone: 'Central',
    totalPUs: 142,
    reportedPUs: 120,
    registeredVoters: 88000,
    bivasAccredited: 40500,
    adcVotes: 17800,
    apcVotes: 21400,
    pdpVotes: 750,
    rejectedVotes: 550,
    cancelledPVCs: 950,
    status: 'TIGHT',
    leadMargin: -3600,
    ec8cSigned: false,
    legalLeadName: 'Barr. Umar Gwandu'
  },
  {
    id: 'lga-06',
    name: 'Bunza',
    zone: 'Central',
    totalPUs: 125,
    reportedPUs: 125,
    registeredVoters: 76000,
    bivasAccredited: 36800,
    adcVotes: 21100,
    apcVotes: 14500,
    pdpVotes: 700,
    rejectedVotes: 500,
    cancelledPVCs: 750,
    status: 'WON',
    leadMargin: 6600,
    ec8cSigned: true,
    legalLeadName: 'Barr. Kabir Bunza'
  },
  {
    id: 'lga-07',
    name: 'Maiyama',
    zone: 'Central',
    totalPUs: 154,
    reportedPUs: 140,
    registeredVoters: 94000,
    bivasAccredited: 43200,
    adcVotes: 23400,
    apcVotes: 18100,
    pdpVotes: 980,
    rejectedVotes: 720,
    cancelledPVCs: 1100,
    status: 'LEADING',
    leadMargin: 5300,
    ec8cSigned: false,
    legalLeadName: 'Barr. Idris Maiyama'
  },
  {
    id: 'lga-08',
    name: 'Koko/Besse',
    zone: 'Central',
    totalPUs: 165,
    reportedPUs: 145,
    registeredVoters: 102000,
    bivasAccredited: 48500,
    adcVotes: 22100,
    apcVotes: 24500,
    pdpVotes: 1100,
    rejectedVotes: 800,
    cancelledPVCs: 1400,
    status: 'TIGHT',
    leadMargin: -2400,
    ec8cSigned: false,
    legalLeadName: 'Barr. Abubakar Koko'
  },
  {
    id: 'lga-09',
    name: 'Argungu',
    zone: 'North',
    totalPUs: 210,
    reportedPUs: 195,
    registeredVoters: 135000,
    bivasAccredited: 69800,
    adcVotes: 36500,
    apcVotes: 31200,
    pdpVotes: 1300,
    rejectedVotes: 800,
    cancelledPVCs: 1600,
    status: 'LEADING',
    leadMargin: 5300,
    ec8cSigned: false,
    legalLeadName: 'Barr. Suleiman Argungu'
  },
  {
    id: 'lga-10',
    name: 'Augie',
    zone: 'North',
    totalPUs: 128,
    reportedPUs: 110,
    registeredVoters: 78000,
    bivasAccredited: 34500,
    adcVotes: 17200,
    apcVotes: 15900,
    pdpVotes: 800,
    rejectedVotes: 600,
    cancelledPVCs: 900,
    status: 'LEADING',
    leadMargin: 1300,
    ec8cSigned: false,
    legalLeadName: 'Barr. Haruna Augie'
  },
  {
    id: 'lga-11',
    name: 'Arewa Dandi',
    zone: 'North',
    totalPUs: 220,
    reportedPUs: 180,
    registeredVoters: 138000,
    bivasAccredited: 62500,
    adcVotes: 28400,
    apcVotes: 32100,
    pdpVotes: 1200,
    rejectedVotes: 800,
    cancelledPVCs: 1700,
    status: 'TIGHT',
    leadMargin: -3700,
    ec8cSigned: false,
    legalLeadName: 'Barr. Ibrahim Arewa'
  },
  {
    id: 'lga-12',
    name: 'Dandi',
    zone: 'North',
    totalPUs: 175,
    reportedPUs: 155,
    registeredVoters: 108000,
    bivasAccredited: 48500,
    adcVotes: 24600,
    apcVotes: 22100,
    pdpVotes: 950,
    rejectedVotes: 850,
    cancelledPVCs: 1150,
    status: 'LEADING',
    leadMargin: 2500,
    ec8cSigned: false,
    legalLeadName: 'Barr. Bello Kamba'
  },
  {
    id: 'lga-13',
    name: 'Bagudo',
    zone: 'North',
    totalPUs: 240,
    reportedPUs: 190,
    registeredVoters: 145000,
    bivasAccredited: 63200,
    adcVotes: 26100,
    apcVotes: 34500,
    pdpVotes: 1400,
    rejectedVotes: 1200,
    cancelledPVCs: 2100,
    status: 'AUDIT_ALERT',
    leadMargin: -8400,
    ec8cSigned: false,
    legalLeadName: 'Barr. Yahaya Bagudo'
  },
  {
    id: 'lga-14',
    name: 'Suru',
    zone: 'North',
    totalPUs: 168,
    reportedPUs: 140,
    registeredVoters: 98000,
    bivasAccredited: 47200,
    adcVotes: 21500,
    apcVotes: 24200,
    pdpVotes: 900,
    rejectedVotes: 600,
    cancelledPVCs: 1300,
    status: 'AUDIT_ALERT',
    leadMargin: -2700,
    ec8cSigned: false,
    legalLeadName: 'Barr. Garba Suru'
  },
  {
    id: 'lga-15',
    name: 'Zuru',
    zone: 'South',
    totalPUs: 215,
    reportedPUs: 215,
    registeredVoters: 132000,
    bivasAccredited: 57400,
    adcVotes: 41200,
    apcVotes: 14200,
    pdpVotes: 1400,
    rejectedVotes: 600,
    cancelledPVCs: 850,
    status: 'WON',
    leadMargin: 27000,
    ec8cSigned: true,
    legalLeadName: 'Barr. Danjuma Zuru'
  },
  {
    id: 'lga-16',
    name: 'Danko/Wasagu',
    zone: 'South',
    totalPUs: 260,
    reportedPUs: 230,
    registeredVoters: 152000,
    bivasAccredited: 58500,
    adcVotes: 38400,
    apcVotes: 18100,
    pdpVotes: 1200,
    rejectedVotes: 800,
    cancelledPVCs: 1650,
    status: 'WON',
    leadMargin: 20300,
    ec8cSigned: false,
    legalLeadName: 'Barr. Yohanna Ribah'
  },
  {
    id: 'lga-17',
    name: 'Fakai',
    zone: 'South',
    totalPUs: 115,
    reportedPUs: 115,
    registeredVoters: 68000,
    bivasAccredited: 31500,
    adcVotes: 19800,
    apcVotes: 10400,
    pdpVotes: 800,
    rejectedVotes: 500,
    cancelledPVCs: 700,
    status: 'WON',
    leadMargin: 9400,
    ec8cSigned: true,
    legalLeadName: 'Barr. Yakubu Fakai'
  },
  {
    id: 'lga-18',
    name: 'Sakaba',
    zone: 'South',
    totalPUs: 105,
    reportedPUs: 105,
    registeredVoters: 62000,
    bivasAccredited: 27800,
    adcVotes: 17600,
    apcVotes: 9100,
    pdpVotes: 700,
    rejectedVotes: 400,
    cancelledPVCs: 600,
    status: 'WON',
    leadMargin: 8500,
    ec8cSigned: true,
    legalLeadName: 'Barr. Bitrus Sakaba'
  },
  {
    id: 'lga-19',
    name: 'Yauri',
    zone: 'South',
    totalPUs: 145,
    reportedPUs: 130,
    registeredVoters: 88000,
    bivasAccredited: 44200,
    adcVotes: 22500,
    apcVotes: 19800,
    pdpVotes: 1100,
    rejectedVotes: 800,
    cancelledPVCs: 1100,
    status: 'LEADING',
    leadMargin: 2700,
    ec8cSigned: false,
    legalLeadName: 'Barr. Aliyu Yauri'
  },
  {
    id: 'lga-20',
    name: 'Shanga',
    zone: 'South',
    totalPUs: 135,
    reportedPUs: 110,
    registeredVoters: 79000,
    bivasAccredited: 36800,
    adcVotes: 16400,
    apcVotes: 18900,
    pdpVotes: 900,
    rejectedVotes: 600,
    cancelledPVCs: 950,
    status: 'TIGHT',
    leadMargin: -2500,
    ec8cSigned: false,
    legalLeadName: 'Barr. Musa Shanga'
  },
  {
    id: 'lga-21',
    name: 'Ngaski',
    zone: 'South',
    totalPUs: 130,
    reportedPUs: 110,
    registeredVoters: 74000,
    bivasAccredited: 34200,
    adcVotes: 15400,
    apcVotes: 17400,
    pdpVotes: 850,
    rejectedVotes: 550,
    cancelledPVCs: 850,
    status: 'TIGHT',
    leadMargin: -2000,
    ec8cSigned: false,
    legalLeadName: 'Barr. Danladi Ngaski'
  }
];

export const INITIAL_INCIDENTS: IncidentReport[] = [
  {
    id: 'INC-9041',
    title: 'Attempted Over-Voting / Ballot Stuffing',
    severity: 'CRITICAL',
    lgaName: 'Bagudo',
    wardName: 'Illo Ward',
    puCode: 'PU 21-13-04-012',
    description: 'Opposition thugs attempted to force presiding officer to accept 45 untracked ballots. BIVAS accreditation was 310, but total cast was 355. ADC agent refused to sign EC8A.',
    reportedBy: 'Ibrahim Illo (PU Agent)',
    reporterPhone: '+234 803 912 3456',
    timestamp: '15 mins ago',
    status: 'LEGAL_DISPATCHED',
    legalCounselAssigned: 'Barr. Yahaya Bagudo',
    actionTaken: 'Protest lodged with Electoral Officer. Police Quick Intervention escorting ballot box to LGA Collation Center.'
  },
  {
    id: 'INC-9038',
    title: 'BIVAS Device Biometric Malfunction',
    severity: 'MAJOR',
    lgaName: 'Danko/Wasagu',
    wardName: 'Ribah Ward',
    puCode: 'PU 21-16-02-007',
    description: 'BIVAS screen froze during facial capture of voter #142. Queue halted for 35 minutes.',
    reportedBy: 'Yohanna Ribah (Ward Supervisor)',
    reporterPhone: '+234 806 882 1199',
    timestamp: '32 mins ago',
    status: 'RESOLVED',
    legalCounselAssigned: 'Barr. Yohanna Ribah',
    actionTaken: 'INEC RATech rebooted device with secondary optical module. Voting resumed; 1 hour time extension granted.'
  },
  {
    id: 'INC-9032',
    title: 'Collation Center Access Denial Attempt',
    severity: 'CRITICAL',
    lgaName: 'Suru',
    wardName: 'Dakingari Ward',
    description: 'Thugs attempted to bar ADC Ward Paralegal from entering the RAC collation hall.',
    reportedBy: 'Salisu Suru (Paralegal)',
    reporterPhone: '+234 814 332 9900',
    timestamp: '48 mins ago',
    status: 'RESOLVED',
    legalCounselAssigned: 'Barr. Garba Suru',
    actionTaken: 'DSS detachment arrived on site. Paralegal seated and inspecting Form EC8B entries.'
  },
  {
    id: 'INC-9021',
    title: 'Late Arrival of Voting Materials',
    severity: 'MINOR',
    lgaName: 'Sakaba',
    wardName: 'Dirindaji Ward',
    puCode: 'PU 21-18-01-003',
    description: 'Materials arrived at 09:45 AM due to bad road terrain. Accreditation started at 10:00 AM.',
    reportedBy: 'Luka Sakaba (Agent)',
    reporterPhone: '+234 802 555 4411',
    timestamp: '2 hours ago',
    status: 'RESOLVED',
    actionTaken: 'INEC presiding officer announced official extension until 04:00 PM.'
  }
];

export const INITIAL_BROADCASTS: BroadcastLog[] = [
  {
    id: 'BC-01',
    sender: 'Central Situation Room (Birnin Kebbi)',
    recipientGroup: 'ALL 3,745 Polling Unit Agents',
    message: 'TACTICAL ALERT: Do NOT sign any Form EC8A if Total Votes Cast exceeds BIVAS Accredited count. Snap EC8A immediately and upload!',
    channel: 'SMS_GATEWAY',
    deliveryCount: 3745,
    timestamp: '14:30 WAT'
  },
  {
    id: 'BC-02',
    sender: 'Malami Legal Shield Command',
    recipientGroup: '225 Ward Paralegals',
    message: 'Audit Ward Form EC8B strictly against sum of PU EC8As. If any variance is discovered, serve instant Notice of Material Variance before sign-off.',
    channel: 'APP_PUSH',
    deliveryCount: 225,
    timestamp: '16:00 WAT'
  }
];

export const ELECTION_STAGES: ElectionStageMeta[] = [
  {
    id: 'STAGE_1_ARRIVAL_SETUP',
    stageNumber: 1,
    name: 'Arrival of INEC Officials & Setup Verification',
    shortName: '1. Arrival & Setup',
    timeWindow: '07:00 AM – 08:30 AM',
    description: 'Verify arrival of Presiding Officer (PO), 3 ad-hoc staff, security officers, and open ballot box inspection.',
    checkQuestions: [
      'Presiding Officer and 3 Ad-hoc polling staff arrived on site?',
      'Accredited security personnel (Police/NSCDC) stationed at the PU?',
      'Ballot box inspected openly and confirmed completely empty before sealing?',
      'Voters Register, official stamps, and indelible ink present and intact?'
    ]
  },
  {
    id: 'STAGE_2_BVAS_ZERO_CHECK',
    stageNumber: 2,
    name: 'BVAS Zero-Accreditation Confirmation',
    shortName: '2. BVAS Zero Check',
    timeWindow: '08:00 AM – 08:30 AM',
    description: 'Mandatory verification that the BVAS accreditation counter reads exactly ZERO (000) before voting commences.',
    checkQuestions: [
      'BVAS screen shown openly to all party agents displaying Zero (0) accredited?',
      'Device battery level exceeds 85% with functional backup power bank present?',
      'PU Code on BVAS screen matches official Kebbi INEC PU designation?',
      'Internal device date & time correctly synchronised with Nigerian WAT?'
    ]
  },
  {
    id: 'STAGE_3_ACCREDITATION_VOTING',
    stageNumber: 3,
    name: 'Poll Commencement & Simultaneous Accreditation/Voting',
    shortName: '3. Accreditation & Voting',
    timeWindow: '08:30 AM – 01:30 PM',
    description: 'Continuous monitoring of voter accreditation pace, priority voting, and BVAS biometric operational health.',
    checkQuestions: [
      'Accreditation and voting commenced simultaneously without impediment?',
      'Strict priority voting given to elderly, pregnant women, and Persons with Disabilities?',
      'Voters marking ballot papers in strict secrecy behind the voting cubicle?',
      'Every voter underwent facial or fingerprint biometric verification on BVAS?'
    ]
  },
  {
    id: 'STAGE_4_QUEUE_CUTOFF',
    stageNumber: 4,
    name: 'Queue Cut-Off at 02:30 PM Prompt',
    shortName: '4. 2:30 PM Queue Lock',
    timeWindow: '02:30 PM Prompt',
    description: 'Strict enforcement of Electoral Act guideline ensuring all voters standing in queue by 2:30 PM are permitted to vote.',
    checkQuestions: [
      'ADC Agent positioned immediately behind the last voter in queue at 2:30 PM?',
      'Presiding Officer announced the close of queue with no new voters allowed to join?',
      'All voters standing in line before 2:30 PM guaranteed their constitutional voting right?'
    ]
  },
  {
    id: 'STAGE_5_BALLOT_SORTING_COUNTING',
    stageNumber: 5,
    name: 'Ballot Sorting & Open Public Counting',
    shortName: '5. Counting & Tallying',
    timeWindow: '02:30 PM – 04:30 PM',
    description: 'Public, open counting and tallying of votes in front of accredited party agents, observers, and security.',
    checkQuestions: [
      'Unused and spoiled ballot papers counted, recorded, and cancelled publicly?',
      'Ballot box opened in full public view and sorted party-by-party (ADC, APC, PDP, etc.)?',
      'Each vote called aloud and shown to party agents and observers?',
      'Disputed ballots resolved strictly according to the Electoral Act 2022 guidelines?'
    ]
  },
  {
    id: 'STAGE_6_EC8A_ENDORSEMENT_UPLOAD',
    stageNumber: 6,
    name: 'Form EEC8A Digital Filing, Photo Upload & Collation Escort',
    shortName: '6. Form EEC8A & Escort',
    timeWindow: '04:30 PM – Conclusion',
    description: 'Digital Form EEC8A entry, Anti-Over-Voting verification, photo capture of signed Form EC8A, and RAC escort.',
    checkQuestions: [
      'Form EC8A scores match the open public count exactly across all parties?',
      'Anti-Over-Voting Engine confirmed Total Votes Cast does NOT exceed BVAS accreditation?',
      'ADC Agent received a clear, signed, certified true duplicate copy of Form EC8A?',
      'ADC Agent actively escorting Presiding Officer and ballot box to Ward Collation Center (RAC)?'
    ]
  }
];

export const INITIAL_PVT_IREV_RECORDS: PVTIReVAuditRecord[] = [
  {
    id: 'PVT-KB-001',
    puCode: 'KB/BK/04/008',
    puName: 'Central Islamiyya School PU 008',
    ward: 'Dangaladima Ward',
    lga: 'Birnin Kebbi',
    registeredVoters: 650,
    agentSubmission: {
      adc: 214,
      apc: 118,
      pdp: 6,
      nnpp: 0,
      lp: 0,
      others: 0,
      accreditedVoters: 342,
      rejectedVotes: 4,
      totalVotesCast: 342,
      photoUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop&q=80',
      timestamp: '2027-03-06 04:42:15 PM',
      gpsCoords: '12.4539° N, 4.1975° E',
      proximityMeters: 6,
      agentName: 'Muhammad Bello Kamba',
      agentPhone: '+234 814 555 1234',
      bvasZeroChecked: true
    },
    irevSubmission: {
      adc: 214,
      apc: 118,
      pdp: 6,
      nnpp: 0,
      lp: 0,
      others: 0,
      accreditedVoters: 342,
      rejectedVotes: 4,
      totalVotesCast: 342,
      sheetUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop&q=80',
      uploadTimestamp: '2027-03-06 05:15:30 PM',
      bvasDeviceId: 'KB-BVAS-BK-008',
      gpsCoords: '12.4540° N, 4.1976° E',
      proximityMeters: 10,
      isBlurredOrIncomplete: false
    },
    status: 'MATCHED',
    voteVariance: { adcDiff: 0, apcDiff: 0, pdpDiff: 0, nnppDiff: 0, lpDiff: 0 },
    timeLagMinutes: 33,
    distanceDiscrepancyMeters: 12,
    flaggedForTribunal: false
  },
  {
    id: 'PVT-KB-002',
    puCode: 'KB/BG/04/012',
    puName: 'Illo Dispensary PU 012',
    ward: 'Illo Ward',
    lga: 'Bagudo',
    registeredVoters: 720,
    agentSubmission: {
      adc: 280,
      apc: 65,
      pdp: 3,
      nnpp: 0,
      lp: 0,
      others: 0,
      accreditedVoters: 350,
      rejectedVotes: 2,
      totalVotesCast: 350,
      photoUrl: 'https://images.unsplash.com/photo-1618042164219-62c820f10723?w=600&auto=format&fit=crop&q=80',
      timestamp: '2027-03-06 04:55:10 PM',
      gpsCoords: '11.5320° N, 3.6540° E',
      proximityMeters: 14,
      agentName: 'Ibrahim Illo',
      agentPhone: '+234 803 912 3456',
      bvasZeroChecked: true
    },
    irevSubmission: {
      adc: 180, // 100 votes stolen from ADC on IReV!
      apc: 165, // 100 votes added to APC on IReV!
      pdp: 3,
      nnpp: 0,
      lp: 0,
      others: 0,
      accreditedVoters: 350,
      rejectedVotes: 2,
      totalVotesCast: 350,
      sheetUrl: 'https://images.unsplash.com/photo-1618042164219-62c820f10723?w=600&auto=format&fit=crop&q=80',
      uploadTimestamp: '2027-03-06 09:22:45 PM',
      bvasDeviceId: 'KB-BVAS-BG-012',
      gpsCoords: '11.4010° N, 4.0210° E', // Uploaded 18.6km away from polling unit!
      proximityMeters: 18600,
      isBlurredOrIncomplete: false
    },
    status: 'VOTE_VARIANCE',
    voteVariance: { adcDiff: -100, apcDiff: 100, pdpDiff: 0, nnppDiff: 0, lpDiff: 0 },
    timeLagMinutes: 267,
    distanceDiscrepancyMeters: 18600,
    flaggedForTribunal: true,
    tribunalEvidenceNotes: 'CRITICAL RIGGING ATTEMPT: Certified Form EC8A duplicate in ADC agent custody shows ADC: 280 vs APC: 65. The sheet uploaded to INEC IReV at 9:22 PM shows altered figures (ADC: 180, APC: 165). BVAS upload GPS confirms device was 18.6km away at Bagudo LGA headquarters.'
  },
  {
    id: 'PVT-KB-003',
    puCode: 'KB/KL/03/002',
    puName: 'Diggi Model Primary School PU 002',
    ward: 'Diggi Ward',
    lga: 'Kalgo',
    registeredVoters: 580,
    agentSubmission: {
      adc: 260,
      apc: 110,
      pdp: 5,
      nnpp: 0,
      lp: 0,
      others: 0,
      accreditedVoters: 380,
      rejectedVotes: 5,
      totalVotesCast: 380,
      photoUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop&q=80',
      timestamp: '2027-03-06 04:35:00 PM',
      gpsCoords: '12.3300° N, 4.1800° E',
      proximityMeters: 8,
      agentName: 'Garba Kalgo',
      agentPhone: '+234 803 222 9988',
      bvasZeroChecked: true
    },
    irevSubmission: {
      adc: 260,
      apc: 145, // APC inflated by +35, causing Total Votes > BVAS Accredited!
      pdp: 5,
      nnpp: 0,
      lp: 0,
      others: 0,
      accreditedVoters: 380,
      rejectedVotes: 5,
      totalVotesCast: 415, // OVER-VOTING ON IREV: 415 > 380!
      sheetUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop&q=80',
      uploadTimestamp: '2027-03-06 07:15:20 PM',
      bvasDeviceId: 'KB-BVAS-KL-002',
      gpsCoords: '12.3305° N, 4.1802° E',
      proximityMeters: 25,
      isBlurredOrIncomplete: false
    },
    status: 'ACCREDITATION_MISMATCH',
    voteVariance: { adcDiff: 0, apcDiff: 35, pdpDiff: 0, nnppDiff: 0, lpDiff: 0 },
    timeLagMinutes: 160,
    distanceDiscrepancyMeters: 30,
    flaggedForTribunal: true,
    tribunalEvidenceNotes: 'OVER-VOTING AUDIT: IReV sheet records 415 total votes cast against only 380 BVAS accredited voters. Statutorily VOID under Section 51(2) of Electoral Act 2022. Tribunal petition ready for full cancellation.'
  },
  {
    id: 'PVT-KB-004',
    puCode: 'KB/AR/02/006',
    puName: 'Gulma Primary School PU 006',
    ward: 'Gulma Ward',
    lga: 'Argungu',
    registeredVoters: 640,
    agentSubmission: {
      adc: 245,
      apc: 92,
      pdp: 4,
      nnpp: 1,
      lp: 0,
      others: 0,
      accreditedVoters: 345,
      rejectedVotes: 3,
      totalVotesCast: 345,
      photoUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop&q=80',
      timestamp: '2027-03-06 04:30:10 PM',
      gpsCoords: '12.7480° N, 4.5320° E',
      proximityMeters: 5,
      agentName: 'Suleiman Argungu Agent',
      agentPhone: '+234 802 777 6655',
      bvasZeroChecked: true
    },
    irevSubmission: {
      adc: 245,
      apc: 92,
      pdp: 4,
      nnpp: 1,
      lp: 0,
      others: 0,
      accreditedVoters: 345,
      rejectedVotes: 3,
      totalVotesCast: 345,
      sheetUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop&q=80',
      uploadTimestamp: '2027-03-06 05:05:00 PM',
      bvasDeviceId: 'KB-BVAS-AR-006',
      gpsCoords: '12.7481° N, 4.5321° E',
      proximityMeters: 8,
      isBlurredOrIncomplete: false
    },
    status: 'MATCHED',
    voteVariance: { adcDiff: 0, apcDiff: 0, pdpDiff: 0, nnppDiff: 0, lpDiff: 0 },
    timeLagMinutes: 35,
    distanceDiscrepancyMeters: 10,
    flaggedForTribunal: false
  },
  {
    id: 'PVT-KB-005',
    puCode: 'KB/ZR/01/009',
    puName: 'Town Hall Square PU 009',
    ward: 'Zuru Urban Ward',
    lga: 'Zuru',
    registeredVoters: 820,
    agentSubmission: {
      adc: 310,
      apc: 125,
      pdp: 2,
      nnpp: 0,
      lp: 0,
      others: 0,
      accreditedVoters: 442,
      rejectedVotes: 5,
      totalVotesCast: 442,
      photoUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop&q=80',
      timestamp: '2027-03-06 04:50:00 PM',
      gpsCoords: '11.4320° N, 5.2340° E',
      proximityMeters: 11,
      agentName: 'Garba Zuru',
      agentPhone: '+234 805 444 8877',
      bvasZeroChecked: true
    },
    irevSubmission: {
      adc: 310,
      apc: 125,
      pdp: 2,
      nnpp: 0,
      lp: 0,
      others: 0,
      accreditedVoters: 442,
      rejectedVotes: 5,
      totalVotesCast: 442,
      sheetUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop&q=80',
      uploadTimestamp: '2027-03-06 05:22:15 PM',
      bvasDeviceId: 'KB-BVAS-ZR-009',
      gpsCoords: '11.4322° N, 5.2341° E',
      proximityMeters: 15,
      isBlurredOrIncomplete: false
    },
    status: 'MATCHED',
    voteVariance: { adcDiff: 0, apcDiff: 0, pdpDiff: 0, nnppDiff: 0, lpDiff: 0 },
    timeLagMinutes: 32,
    distanceDiscrepancyMeters: 16,
    flaggedForTribunal: false
  },
  {
    id: 'PVT-KB-006',
    puCode: 'KB/AL/01/004',
    puName: 'Aliero Central Model PU 004',
    ward: 'Aliero Dangaladima',
    lga: 'Aliero',
    registeredVoters: 760,
    agentSubmission: {
      adc: 275,
      apc: 130,
      pdp: 5,
      nnpp: 0,
      lp: 0,
      others: 0,
      accreditedVoters: 414,
      rejectedVotes: 4,
      totalVotesCast: 414,
      photoUrl: 'https://images.unsplash.com/photo-1618042164219-62c820f10723?w=600&auto=format&fit=crop&q=80',
      timestamp: '2027-03-06 04:35:00 PM',
      gpsCoords: '12.2890° N, 4.4980° E',
      proximityMeters: 7,
      agentName: 'Murtala Aliero Agent',
      agentPhone: '+234 814 222 5533',
      bvasZeroChecked: true
    },
    irevSubmission: {
      adc: 275,
      apc: 130,
      pdp: 5,
      nnpp: 0,
      lp: 0,
      others: 0,
      accreditedVoters: 414,
      rejectedVotes: 4,
      totalVotesCast: 414,
      sheetUrl: 'https://images.unsplash.com/photo-1618042164219-62c820f10723?w=600&auto=format&fit=crop&q=80',
      uploadTimestamp: '2027-03-06 10:48:10 PM', // Delayed upload by over 6 hours!
      bvasDeviceId: 'KB-BVAS-AL-004',
      gpsCoords: '12.2885° N, 4.4975° E',
      proximityMeters: 80,
      isBlurredOrIncomplete: false
    },
    status: 'TIME_LAG_ALERT',
    voteVariance: { adcDiff: 0, apcDiff: 0, pdpDiff: 0, nnppDiff: 0, lpDiff: 0 },
    timeLagMinutes: 373,
    distanceDiscrepancyMeters: 85,
    flaggedForTribunal: true,
    tribunalEvidenceNotes: 'SUSPICIOUS TIME LAG: Result was completed and signed at 4:35 PM, but IReV upload did not occur until 10:48 PM (6+ hours delay). Flagged for chain-of-custody interrogation.'
  },
  {
    id: 'PVT-KB-007',
    puCode: 'KB/JG/05/011',
    puName: 'Kimba Health Clinic PU 011',
    ward: 'Kimba Ward',
    lga: 'Jega',
    registeredVoters: 610,
    agentSubmission: {
      adc: 228,
      apc: 95,
      pdp: 4,
      nnpp: 0,
      lp: 0,
      others: 0,
      accreditedVoters: 330,
      rejectedVotes: 3,
      totalVotesCast: 330,
      photoUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop&q=80',
      timestamp: '2027-03-06 04:40:00 PM',
      gpsCoords: '12.2200° N, 4.3800° E',
      proximityMeters: 6,
      agentName: 'Sani Jega Agent',
      agentPhone: '+234 803 777 1144',
      bvasZeroChecked: true
    },
    irevSubmission: {
      adc: 228,
      apc: 95,
      pdp: 4,
      nnpp: 0,
      lp: 0,
      others: 0,
      accreditedVoters: 330,
      rejectedVotes: 3,
      totalVotesCast: 330,
      sheetUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop&q=80',
      uploadTimestamp: '2027-03-06 05:18:22 PM',
      bvasDeviceId: 'KB-BVAS-JG-011',
      gpsCoords: '12.2201° N, 4.3801° E',
      proximityMeters: 9,
      isBlurredOrIncomplete: false
    },
    status: 'MATCHED',
    voteVariance: { adcDiff: 0, apcDiff: 0, pdpDiff: 0, nnppDiff: 0, lpDiff: 0 },
    timeLagMinutes: 38,
    distanceDiscrepancyMeters: 11,
    flaggedForTribunal: false
  },
  {
    id: 'PVT-KB-008',
    puCode: 'KB/YR/01/003',
    puName: 'Emir Palace Square PU 003',
    ward: 'Yauri Urban Ward',
    lga: 'Yauri',
    registeredVoters: 780,
    agentSubmission: {
      adc: 275,
      apc: 140,
      pdp: 2,
      nnpp: 0,
      lp: 0,
      others: 0,
      accreditedVoters: 420,
      rejectedVotes: 3,
      totalVotesCast: 420,
      photoUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop&q=80',
      timestamp: '2027-03-06 04:45:00 PM',
      gpsCoords: '10.7800° N, 4.7700° E',
      proximityMeters: 10,
      agentName: 'Aliyu Yauri Agent',
      agentPhone: '+234 806 333 9922',
      bvasZeroChecked: true
    },
    irevSubmission: {
      adc: 275,
      apc: 140,
      pdp: 2,
      nnpp: 0,
      lp: 0,
      others: 0,
      accreditedVoters: 420,
      rejectedVotes: 3,
      totalVotesCast: 420,
      sheetUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop&q=80',
      uploadTimestamp: '2027-03-06 05:25:40 PM',
      bvasDeviceId: 'KB-BVAS-YR-003',
      gpsCoords: '10.7802° N, 4.7701° E',
      proximityMeters: 14,
      isBlurredOrIncomplete: false
    },
    status: 'MATCHED',
    voteVariance: { adcDiff: 0, apcDiff: 0, pdpDiff: 0, nnppDiff: 0, lpDiff: 0 },
    timeLagMinutes: 40,
    distanceDiscrepancyMeters: 15,
    flaggedForTribunal: false
  }
];

